### ISSUE TITLE
Area price calculation doesn't work with quantity pricing.

### ISSUE THREAD

**Issue by nooysters** [spree-contrib-variants/spree_product_customizations#10]
I am not sure if others would find this useful, but for my use case the calculation needs to be
total_area \* price_per_qty, that way other options that modify on the quantity price will change the area price per unit^2 as well. At least that is how I believe it will work, I'm going to give it a go. Appreciate any thoughts.

**Comment by sfcgeorge** [comment]
For my client's site he needed curtain area pricing. It had to be the fabric base price (the variant e.g. $10) multiplied by the area with the cost of making added on. So in the below code the base price can be grabbed from the variant, then do your calculations and subtract the price otherwise it'll be in there twice.

``` ruby
def compute(product_customization, variant=nil)
  price = product_customization.line_item.variant.price
  # ...
  making + (fabric_multiplier * price) - price
end
```

I'm not sure if that makes sense or is what you're asking, but I think the `price` line might help you?

**Comment by nooysters** [comment]
Yes, this looks like what I need. I will implement it in a custom calculator. I am working on a wallpaper site that is sold in a similar way.

**Comment by sfcgeorge** [comment]
Great. For the JavaScript calculator you can use `base_price` which is a global variable I believe.

No monkeypatching of this gem is needed, you can do it all in your app:

The calculator files go in your app's directories like this:
<img width="285" alt="screen shot 2015-10-15 at 00 47 20" src="https://cloud.githubusercontent.com/assets/885003/10501158/7449da3c-72d6-11e5-9bba-47a8bea64564.png">

Then to register the custom calculator you do it in `config/application.rb`:

``` ruby
module MyApp
  class Application < Rails::Application
    # ...

    initializer "InteriorSuperstore.register.calculators" do |app|
      app.config.spree.calculators.product_customization_types.push(
        Spree::Calculator::CurtainArea, Spree::Calculator::CushionArea
      )
    end
  end
end
```

**Comment by nooysters** [comment]
I'm getting an the following error:

/config/application.rb:26:in `block in class:Application': uninitialized constant Spree::Calculator::MuralArea (NameError)

in config/application.rb

 initializer "DywOnRails.register.calculators" do |app|
      app.config.spree.calculators.product_customization_types.push(
        Spree::Calculator::MuralArea
      )
    end

![screen shot 2015-10-14 at 5 19 36 pm](https://cloud.githubusercontent.com/assets/1557527/10501566/f31f1514-7297-11e5-81d0-5ee2055d1900.png)

Any ideas what I'm doing wrong?

**Comment by nooysters** [comment]
Just copied the calculator code and changed the name like so:

module Spree
  class Calculator::MuralArea < Calculator
    preference :multiplier, :decimal

```
preference :min_pricing_area, :integer  # the minimum size we'll use for pricing (we might sell you a 4x4, but we'll charge u for a 10x10

preference :min_width, :integer, :default => 0
preference :max_width, :integer, :default => 100

preference :min_height, :integer, :default => 0
preference :max_height, :integer, :default => 100

#attr_accessible :preferred_multiplier, :preferred_min_pricing_area, :preferred_min_width, :preferred_max_width,:preferred_min_height, :preferred_max_height

# preference :min_area, :integer  # the minimum sized frame we'll sell

# these can be reflected in the custom partials?
#  preference :measurement_units, :string, :default => 'inches'
#  preference :granularity, :string, :default => 'eighths'

def self.description
  "Mural Area Calculator"
end

def self.register
  super
  ProductCustomizationType.register_calculator(self)
end

def create_options
  # This calculator knows that it needs two CustomizableOptions, width & height
  [
   CustomizableProductOption.create(:name=>"width", :presentation=>"Width"),
   CustomizableProductOption.create(:name=>"height", :presentation=>"Height")
  ]
end

# as object we always get line items, as calculable we have Coupon, ShippingMethod
def compute(product_customization, variant=nil)
  return 0 unless valid_configuration? product_customization

  width,height = get_option(product_customization, "width"), get_option(product_customization, "height")

  # here's the custom logic for this calculator:  min total width + height = 20.
  [(width.value.to_f * height.value.to_f), (preferred_min_pricing_area || 0)].max * preferred_multiplier
end

def valid_configuration?(product_customization)
  # expecting exactly two CustomizedProductOptions

  all_opts = product_customization.customized_product_options.map {|cpo| cpo.customizable_product_option.name }

  # do we have the necessary inputs?
  has_inputs = all_opts.include?("width") && all_opts.include?("height")

  # do the inputs meet the criteria?
  width,height = get_option(product_customization, "width"), get_option(product_customization, "height")

  #    return has_inputs && width && height && (width.value.to_f * height.value.to_f) >= preferred_min_area

  #    rescue false
  return true
end


private
def get_option(product_customization, name)
  product_customization.customized_product_options.detect {|cpo| cpo.customizable_product_option.name == name }
end
```

  end
end

**Comment by nooysters** [comment]
Nevermind I named the calculator folder pluralized. doh!
