### ISSUE TITLE
calculator_types need updating

### ISSUE THREAD

**Issue by nooysters** [spree-contrib-variants/spree_product_customizations#4]
Every time I add a customized product to cart I get the following

NoMethodError in Spree::OrdersController#populate
undefined method `empty?' for nil:NilClass

![screen shot 2015-07-21 at 5 23 00 pm](https://cloud.githubusercontent.com/assets/1557527/8815388/3be8a4e4-2fcd-11e5-8ba9-27caaef29c9a.png)

**Comment by sfcgeorge** [comment]
Yep, I know what's happening here. Latest Spree and Rails use StrongParameters to only allow known inputs. This extension however is all about custom inputs that were previously impossible to whitelist. I changed the form data structure to make it white-listable. 

You can see the new format in [Amount Times Constant calculator](https://github.com/spree-contrib-variants/spree_product_customizations/blob/master/app/views/spree/products/customizations/calculator_type/_amount_times_constant.html.erb). That's the only one I've updated so far so I guess you're using one of the other calculators or a custom one.

It's an easy fix. You can send a pull request updating the other calculators to the new style, or wait a few days for me to do it.

**Comment by nooysters** [comment]
It seems to be working now I sent the pull request for the area calculator. Will work on the others when I get a chance.

**Comment by sfcgeorge** [comment]
Thank you! Fantastic getting contributions. The code looked fine so I merged it. 

I haven't mentioned it anywhere yet but it would be good in future to work to a styleguide, [Rubocop](https://github.com/bbatsov/rubocop) is a popular automated one. But a lot of the current code is a mess so don't worry about it, I'm just happy to get the bugs fixed :)

**Comment by nooysters** [comment]
Rubocop doesn't work so good for views files all the offenses were related to unexpected "<" at the beginning of erb tags. I may be using it wrong, it's my first time.

**Comment by sfcgeorge** [comment]
Hmm [you're right](https://github.com/bbatsov/rubocop/issues/1113) it's not supported and they're not going to. Really there's far too much logic in the views anyway. Don't worry about it, you could skim the [ruby style guide](https://github.com/bbatsov/ruby-style-guide) if you have time but as the views are already complicated I'll accept any bug fixes with reasonable style.

**Comment by sfcgeorge** [comment]
I've also added you as a contributor to the org making it easier for you to contribute if you wish

**Comment by nooysters** [comment]
Thanks!
