### ISSUE TITLE
error when adding a product variant to the cart a second time, when it does not have product customizations.

### ISSUE THREAD

**Issue by nooysters** [spree-contrib-variants/spree_product_customizations#9]
Basically we have products with an option for sample or full order. These products are not using product_customizations. The first time you add a sample to the cart it works fine. The second time we get the following error:

undefined method `product_customizations' for {}:Hash

Extracted source (around line #21):

```
    new_vals = Set.new a
  else
    new_customizations = new_customizations.product_customizations

    # if there aren't any customizations, there's a 'match'
    return true if existing_customizations.empty? && new_customizations.empty?
```

Rails.root: /Users/jeremy/Development/Rails/designyourwall_spree/dyw_on_rails

**Comment by nooysters** [comment]
I added a guard statement at the top of order_decorator.rb 

module Spree
  Order.class_eval do
    def product_customizations_match(line_item, new_customizations)

```
  # Guard against items without customizations.
  return true if new_customizations.empty?

  existing_customizations = line_item.product_customizations
```

It seems to prevent the error and allow the products with the customizations to still work properly. Although product_customizations_match really shouldn't be called at all.

**Comment by sfcgeorge** [comment]
Spree calls it to check if there's a match, so possibly it should return false in this case? I'm not quite Sure what that Spree API means. But yes it looks like a guard clause is necessary.

**Comment by nooysters** [comment]
Based on the following line

```
    # if there aren't any customizations, there's a 'match'
    return true if existing_customizations.empty? && new_customizations.empty?
```

it seems like returning true is what it wants. Returning false creates a new line item while returning true will increment the quantity of the existing line item (more desirable, in my case at least.)

**Comment by sfcgeorge** [comment]
Perfect, I remembered seeing a line about that somewhere. Thank you for the fix and helpful comment; it's such a fiddly extension that comments like that are really useful.
